language: python
python:
  - 2.7
  - 3.4
  - 3.5

sudo: false

# Setup anaconda following http://conda.pydata.org/docs/travis.html#the-travis-yml-file
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash ./miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  # For tests with plot instructions
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

# Install packages
install:
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pip numpy matplotlib scipy numba pytest-cov
  - source activate test-environment

before_script:
  - pip install coveralls
  - pip install -r requirements.txt
  - pip install .

# Run test
script:
  - py.test --cov --cov-report=term-missing

# Calculate coverage
after_success:
  - coveralls --config_file .coveragerc

